name: Unit testing

on:
  - push
  - workflow_dispatch

env:
  EARTHENGINE_TOKEN: ${{ secrets.EARTHENGINE_TOKEN }}
  PLANET_API_KEY: ${{ secrets.PLANET_API_KEY }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - uses: pre-commit/action@v3.0.0
      - name: Install module venv
        run: |
          python -m pip install "git+https://github.com/12rambau/sepal_ui.git@sepal_pre_release"
          module_venv --venv_prefix venv
      - name: Activate venv
        run: source ~/module-venv/clip-time-series/bin/activate
      - name: install nbmake
        run: python -m pip install pytest nbmake
      - name: build the application
        run: pytest --nbmake ui.ipynb
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install module venv
        run: |
          python -m pip install "git+https://github.com/12rambau/sepal_ui.git@sepal_pre_release"
          module_venv --venv_prefix venv
      - name: Activate venv
        run: source ~/module-venv/clip-time-series/bin/activate
      - name: run tests
        run: python -m pytest test/
