name: Unit testing

on:
  - push
  - workflow_dispatch

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - uses: pre-commit/action@v3.0.0
      - name: install dependencies
        run: |
          python -m pip install --find-links=https://girder.github.io/large_image_wheels GDAL
          python -m pip install earthengine-api
          python -m pip install -r requirements.txt
          python -m pip install pytest nbmake
      - name: build the application
        run: pytest --nbmake ui.ipynb
